

services:

  cmsserver:
    build:
      context: ./config/lucee-cms/
      args:
        LUCEE_ADMIN_PASSWORD: contens
      dockerfile: lucee-cms.Dockerfile
    container_name: coldfusion_app
    hostname: cfadmin.dev
    volumes:
      - ../../html:/var/www.cms.goethe.de/html
      - shared_configs:/opt/coldfusion/config/wsconfig/
      - shared_www:/opt/coldfusion/cfusion/wwwroot/
      - ../../lib/:/usr/local/tomcat/contenslib/
    ports:
      - '8888:8888'
    depends_on:
      - cmsweb
      - elasticsearch
    networks:
      apachecf:
        ipv4_address: 10.6.0.5

  cmsweb:
    build:
      context: ./config/apache-cms/
      dockerfile: apache-cms.Dockerfile
    container_name: http-proxy
    hostname: cmsdev.goethe.de
    volumes:
      - shared_configs:/opt/coldfusion/config/wsconfig/
      - shared_www:/opt/coldfusion/cfusion/wwwroot/
      - ./logs:/var/log/apache2
      - ../../html:/var/www.cms.goethe.de/html
    ports:
      - '80:80'
      - '443:443'
    networks:
      apachecf:
        ipv4_address: 10.6.0.6

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14@sha256:5e9a5614a90e828b40fcca7ea12bf11516b99a1afa7e0cb3b6d1c9f3097b19e1
#    container_name: elasticsearch
#    restart: always
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    cap_add:
#      - IPC_LOCK
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    networks:
#      apachecf:
#        ipv4_address: 10.6.0.7
#
#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:7.17.14@sha256:a68b98d386f222151b87251a1be7d4af4a75267f6b54d9fe63747495feb2a028
#    restart: always
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch
#    networks:
#      apachecf:
#        ipv4_address: 10.6.0.8

volumes:
  shared_configs:
  shared_www:
  elasticsearch-data:

networks:
  apachecf:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1